### PR TITLE
fix inertia: take care of the case when t is zero

### PR DESCRIPTION
**Pull request by chuganzy**
This PR aims to fix an issue where `Reorder.Item` randomly gets stuck as I posted [here](https://github.com/framer/motion/pull/2231#issuecomment-1655992476).

Related:
* https://github.com/framer/motion/issues/2101
* https://github.com/framer/motion/pull/2231

As noted [here](https://github.com/framer/motion/blob/main/packages/framer-motion/src/animation/animators/js/index.ts#L138-L141):

> requestAnimationFrame timestamps can come through as lower than the startTime

which means that `startTime` possibly can be equal to `currentTime` and `t` is 0 in that case. `inertia` returns the state with `done: true`  in that case, and stops the animation immediately.

### CODE REVIEW

**Comment by mattgperry** [comment]
Is it possible to add a test on `inertia` for this behaviour?

**Comment by ekatzenstein** [comment]
Is there an update on this PR? Having issues with reorders as well

**Comment by nick-keller** [comment]
@ekatzenstein their is this PR #2231 waiting to be merged as well

**Comment by davisg123** [comment]
Is there anything blocking getting this merged in? It seems like a high impact, edge case fix that includes a test

**Comment by nick-keller** [comment]
Shouldn't this be merged? It looks like a very simple fix that is tested. Or maybe I am missing something?

**Comment by marwhyte** [comment]
Is there an update on this? I'm also having similar issues with reordering

**Comment by bel0v** [comment]
@mattgperry any chance we could have these 2 PRs merged please? The issue has been affecting our production for a while too

**Comment by nick-keller** [comment]
Seeing the recent activity, I am bringing this PR up again! @mattgperry it is the last brik to fix the re-order component that is broken!

**Comment by mattgperry** [comment]
Closing as the added failing test was fixed by a update in the meantime (changing the `>` on that line to a `>=`)

**Pull request closed without merging**
