### PR TITLE
update list of camel case svg attributes

### PR DESCRIPTION
**Pull request by KirdesMF**
#1152 
it should be good now

### CODE REVIEW

**Comment by KirdesMF** [comment]
https://codesandbox.io/s/framer-motion-simple-animation-forked-j53vx?file=/src/Example.tsx

**Comment by mattgperry** [comment]
Thanks for this. I'm wondering though, given how obscure all these attr names are, if there's a way we could get rid of the array altogether.

**Comment by rijk** [comment]
@mattgperry could we merge this in the meantime? Because it's currently not possible to animate these properties.

**Comment by rijk** [comment]
Hm, I found that monkey patching this array didn't fix the issue for me.. Debugging, it seems `renderSVG` is not called at all? 🤔

**Comment by mattgperry** [comment]
@rijk Is this still true with the latest version of Motion? Which element and attribute were you animating? 

Closing this out though as I'd rather these quite obscure props weren't animatable than add the extra bundlesize.

**Comment by rijk** [comment]
Hi @mattgperry ! Yup, I am using `6.3.3` and it was not working. I was trying to animate `startOffset` for the scroll-triggered marquee text [on this site](https://made-baron.vercel.app). But when I tried to do this:

```jsx
<motion.textPath href="#path" startOffset={offset}>
  {children}
</motion.textPath>
```

it didn't work because it incorrectly converts the attribute to `start-offset`. So I had to resort to this:

```ts
useEffect(() => {
  return pathOffset.onChange((v) => {
    path.current?.setAttribute('startOffset', v)
  })
}, [])
```

which works but I think doesn't perform as well.

**Comment by rijk** [comment]
Very annoying that the SVG attributes [are so inconsistent](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute).. I was thinking you could maybe assume camelCase when in an SVG context, but `glyph-orientation-vertical` vs `glyphRef`, `marker-start` vs `markerWidth`.. there is no logic to the naming it seems they just flipped a coin 🤔

**Edit:** ahh, the dash-case ones are apparently what they call "[Presentation attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#presentation_attributes)". That is why they are not camelCased:

>  SVG presentation attributes are CSS properties that can be used as attributes on SVG elements.

**Comment by rijk** [comment]
So knowing this, I think a way to do it without bloating the bundle with a hardcoded list is to default to camelCase for SVG, and only use dash-case (not sure what the official name for that is) for these CSS presentational attributes;

```js
const svg = document.createElement('svg')
const key = attribute in svg.style ? property : camelCase(attribute)
```

Or more to the point of [the code](https://github.com/framer/motion/blob/f39eb0730d75ada35437e20dd8cff8284030f7eb/packages/framer-motion/src/render/svg/visual-element.ts#L28):

```js
key = camelToDash(key) in domElement.style ? camelToDash(key) : key
```

**Comment by mattgperry** [comment]
That's very clever. I wonder how it can be done with SSR in mind. I think this is a good starting place though.

**Comment by rijk** [comment]
Aren’t these functions (get/set current animation value) by their nature only run on the client?

**Comment by mattgperry** [comment]
Yeah but off the top of my head we also output JSX to SSR the initial state

**Pull request closed without merging**
