### PR TITLE
Updated `@emotion/is-valid-prop`

### PR DESCRIPTION
**Pull request by iam-medvedev**
Changed the way the `@emotion/is-valid-prop` dependency is defined.

Optional peer dependency is less strict - it doesn't touch the lockfile signature and allows you to use any version in your project.

NOTE: I chose the `*` version and it's safe since the package API has never changed.

Closes https://github.com/framer/motion/issues/2530

### CODE REVIEW

**Comment by mattgperry** [comment]
Great, thanks for this!

**Comment by nimaa77** [comment]
this change broke my app after I upgraded to `11.0.13`

the error says

```bash
Import trace for requested module:
./node_modules/framer-motion/dist/es/render/dom/utils/filter-props.mjs
./node_modules/framer-motion/dist/es/index.mjs
./src/components/Header/Header.tsx
 ⚠ ./node_modules/framer-motion/dist/es/render/dom/utils/filter-props.mjs
Module not found: Can't resolve '@emotion/is-prop-valid' in 'node_modules/framer-motion/dist/es/render/dom/utils'

Import trace for requested module:
./node_modules/framer-motion/dist/es/render/dom/utils/filter-props.mjs
./node_modules/framer-motion/dist/es/index.mjs
./src/components/Header/Header.tsx
```

**Comment by iam-medvedev** [comment]
@nimaa77 Could you provide code that can be reproduced?

**Comment by italodeandra** [comment]
```
 ⚠ ./node_modules/framer-motion/dist/cjs/index.js
Module not found: Can't resolve '@emotion/is-prop-valid' in 'C:\Users\user\WebstormProjects\marketplace-ui\node_modules\framer-motion\dist\cjs'

Import trace for requested module:
./node_modules/framer-motion/dist/cjs/index.js
```

Getting this error from any `11.*.*` version.

**Comment by tyxla** [comment]
> ```
>  ⚠ ./node_modules/framer-motion/dist/cjs/index.js
> Module not found: Can't resolve '@emotion/is-prop-valid' in 'C:\Users\user\WebstormProjects\marketplace-ui\node_modules\framer-motion\dist\cjs'
> 
> Import trace for requested module:
> ./node_modules/framer-motion/dist/cjs/index.js
> ```
> 
> Getting this error from all `11.*.*` versions.

We solved this error by specifically adding `emotion/is-prop-valid` as a dev dependency (see https://github.com/WordPress/gutenberg/pull/68202).

**Pull request merged**
