### PR TITLE
feat: add patchMotionTags for legacy browsers which don't support Proxy

### PR DESCRIPTION
**Pull request by ambar**
Related: #364 #664 #674 #1178

## Usage
```js
import {patchMotionTags} from 'framer-motion'

patchMotionTags()
```

Test result:
| Tool | Bundle Diff | 
| --- | --- | 
| webpack | +1070B (gzip 464B) |
| esbuild | +1068B (gzip 469B) |

---
A less convenient solution is to rewrite export, but it will significantly increase the bundle size:

```js   
export let motion = motionProxy
// motion will always be bundled
export const patchMotion = () => {
    motion = createMotionFallback()
}
```

### CODE REVIEW

**Comment by ppsirius** [comment]
What is the status of this?

**Comment by mattgperry** [comment]
Sorry for the delay on this but closing this out as the point of using `Proxy` in the first place is to avoid having to maintain a list of valid tags that has to be then included in the bundle.

**Comment by ambar** [comment]
The DOM tags in this patch would not be bundled unless you call `patchMotionTags()`.

Right now, all other workarounds are a little pain to use:

- `yarn patch` requires line number of source code (unstable)
- Aliasing requires different bundler config in different projects (and also, we may need to inject a fake Proxy polyfill and then revert it)
- Re-exporting m/motion from another package (we end up with this)

**Comment by mattgperry** [comment]
They would be included though, because the bundler has no way of knowing whether `patchMotionTags` is going to be called by the client.

**Pull request closed without merging**
