### PR TITLE
2

### PR DESCRIPTION
**Pull request by InventingWithMonster**
**This PR is a WIP and isn't ready for review.**

This PR introduces Magic Motion to Framer Motion. Magic Motion replaces `positionTransition` and `layoutTransition` with  the `animate={true}` prop and adds the `AnimateSharedLayout` component.

# About

When `animate` is`true`, layout and style changes that happen as a result of a re-render are automatically detected and animated.

## Layout

Layout animations are performed using the [FLIP method](https://aerotwist.com/blog/flip-your-animations/). This emulates the animation of expensive layout with transforms. Usually, animating dimensions with this technique leads to distortion on the element and any children.

Auto-animate components correct visual distortion on size, borderRadius and boxShadow, as well as full-tree correction on any child auto-animate components.

## Styles

Automatically detected styles are `backgroundColor`, `borderRadius`, `borderTopLeftRadius`, `borderTopRightRadius`, `borderBottomLeftRadius`, `borderBottomRightRadius`, `boxShadow`, `color` and `opacity`.

## Shared element transitions

The `AnimateSharedLayout` component enables components to be tagged with the `layoutId` property. When a new component with an existing `layoutId` enters the tree, it will visually animate from the existing component.

If the existing component persists in the tree, `AnimateSharedLayout` can either hide it instantly (`type="switch"`) or crossfade between the two elements (`type="crossfade"`).

If the new component is placed within `AnimatePresence`, it will automatically animate back to the original component when removed from the tree.

# Examples

- [Switch](https://codesandbox.io/s/framer-motion-magic-motion-switch-demo-0d68e)
- [Scale-corrected borderRadius and boxShadow demo](https://codesandbox.io/s/framer-motion-magic-motion-simple-reparenting-demo-m6qp0)
- [Reparenting demo](https://codesandbox.io/s/framer-motion-magic-motion-reparenting-demo-7x9id)
- [Menu selection](https://codesandbox.io/s/framer-motion-magic-motion-underline-menu-demo-y6tl3)
- [Accordion](https://codesandbox.io/s/framer-motion-magic-motion-accordion-demo-tqzul)
- [Gallery](https://codesandbox.io/s/framer-motion-magic-motion-gallery-demo-pknk7)
- [App store](https://codesandbox.io/s/framer-motion-magic-motion-app-store-demo-su6mx)

# TODO

- [x] Finalise API
- [ ] Pop leaving `AnimatePresence` children out of the document flow
- [ ] Drag integration
- [x] Clean up examples
- [ ] Improve comments
- [x] Move useAnimatedState to 'framer'
- [ ] Write tests

### CODE REVIEW

**Comment by subvertallchris** [comment]
Hey Matt, love your work on this library and this feature looks perfect for something I'm struggling with right now. If you don't mind me asking, what's your sense of timing on when we can expect this and a production V2 release? Do you think the beta is stable enough right now that it could be used in production or should we hold off? Since it's a major version, I'm guessing there must be some breaking changes -- are those documented anywhere I could peek at?

Thanks for all of your work!

**Comment by msheakoski** [comment]
@subvertallchris Matt posts V2-related stuff to his [Twitter](https://twitter.com/mattgperry) quite often. In addition to news, there are many examples showing off the new features and ideas.

**Comment by InventingWithMonster** [comment]
The breaking changes are the removal of positionTransition and layoutTransition in favour of animate. It’s pretty stable and we use it in Framer already but I am working through bugs so things can break. You will probably want to lock your version at least

**Comment by subvertallchris** [comment]
Great stuff. Thanks, guys!

**Pull request closed without merging**
