### PR TITLE
Add optional chaining to navigator.userAgent

### PR DESCRIPTION
**Pull request by TerminalStar**
Closes https://github.com/framer/motion/issues/2371

### CODE REVIEW

**Review by ziishaned — APPROVED** [review]

**Comment by rmill2016** [comment]
Please merge 😭

**Comment by TerminalStar** [comment]
@mattgperry can you help to get this merged in? 🙏

**Comment by rmill2016** [comment]
> @mattgperry can you help to get this merged in? 🙏

Someone else on another thread recommends downgrading Node version to resolve this temporarily, have you tried this yet?

**Comment by TerminalStar** [comment]
@rmill2016 yes, downgrading works but I came across this as we were looking upgrade to v21 to fix a security vulnerability. Node v21.1.0 has [added the `userAgent` property back](https://github.com/nodejs/node/releases/tag/v21.1.0) so we can upgrade to that version without this change.

That said, I would still support it being merged in as it makes the code more resilient to being run in environments with different shapes of `navigator` object - notably this is the only dependency of ours that doesn't somehow check for `userAgent` before accessing it. But given I can bump the node version in my project now, I don't feel strongly about it and the maintainers can do as they wish 🤷‍♀️

**Comment by mattgperry** [comment]
I'm just going to close this out as this is specced so **should** (imo) be treated as a bug from the implementor.

**Pull request closed without merging**
