### PR TITLE
Fix projection of fixed elements when scrolling

### PR DESCRIPTION
**Pull request by koop**
Fixes the failing `position: fixed;` projection tests added in #1768.
- I verified that all other projection tests still passed (I verified this manually because I couldn't get the cypress configuration to run on my local machine).

Fixes issues #2514, #2006, and #1972.

| Before  | After |
| ------------- | ------------- |
| [Sandbox to reproduce the issue](https://codesandbox.io/p/devbox/framer-motion-fixed-projection-bug-yzsrql?file=%2Fsrc%2FApp.tsx)  | [Sandbox to verify fix (with patch applied)](https://codesandbox.io/p/devbox/framer-motion-fixed-projection-fix-with-patch-7gx7pl?file=%2Fsrc%2FApp.tsx%3A9%2C26)  |
|  |  |

### Details

**To handle projecting fixed elements within scrollable pages:** as I understand it, the existing logic accounted for scroll root ancestors within `removeElementScroll` by iterating over the `path`, but this didn't account for the case where the current element was a fixed element, because the `path` does not contain the current node. Instead, we now avoid adding the scroll position in `measurePageBox` when the projection is or is within a fixed element.

**To handle projected fixed elements within scrollable elements:** this was a similar case where we weren't accounting for the current element's scroll information. If the current element is fixed, we can return early from `removeElementScroll`.

**To handle projecting when an element changes between fixed and static positions:** we track whether the position was fixed during the snapshot phase (instead of relying on the most recently measured value) and use that to determine whether the projection considers an element fixed or not. Two considerations here:
- I'm not sure about the nuances of resuming projections and whether or not there would be a more correct way to track this information.
- This does not solve for the case where an element transitions between `position: sticky;` and `position: fixed;`. Fixing this may involve tracking more than just whether or not the element is fixed when the snapshot is taken; I haven't spent enough time with that failing test case.

### CODE REVIEW

**Comment by koop** [comment]
Sounds good!

> We don't need to worry so much about position: sticky - stickied elements themselves can flick between "fixed" and "static" modes and there's no good way of tracking this.

That's roughly what I expected (and why I didn't include it here), monitoring sticky position/state is a pain.

**Comment by lilingxi01** [comment]
Thank you for making this PR! This could resolve a lot of transition glitches related to `position: fixed`.

**Comment by Thanaen** [comment]
Is it possible to finance this PR (via [Polar.sh](https://polar.sh/) for example) to support the work needed to merge it? 😄

**Comment by mattgperry** [comment]
Thanks for this excellent PR and apologises for the delay. I'm merging into an intermediate branch to try it out and if all tests are running well I'll publish in next couple days.

**Pull request merged**
