### PR TITLE
Comparing origin/target before starting new layout animation

### PR DESCRIPTION
**Pull request by mattgperry**
Fixes https://github.com/framer/motion/issues/807

### CODE REVIEW

**Review by hemlok — APPROVED** [review]
Makes sense 👌

**Comment by johnnybenson** [comment]
Is this okay to merge?

**Comment by rijk** [comment]
Here's another sandbox: https://codesandbox.io/s/condescending-keller-s5u28, as you can see when closing the modal it also keeps restarting the animation from 1 opacity, and the exit animation never finishes. Hope this change fixes that as well. In my app I have a similar modal with `layoutId` that because of a state change never reaches opacity: 1 but remains stuck on opacity: 0.962834. I tried to reproduce that here but couldn't unfortunately.

**Comment by rijk** [comment]
@mattgperry sorry to spam, but this one is super annoying and comes up a lot. Basically every state change (loading data, measuring bounds, etc) that happens during a layout transition trips it up. There is not really a way to work around it, except by delaying the state updates, which in some cases (like a `ResizeObserver`) is not even possible. So it's kind of a show stopper for `layout` in those cases. If this fix is good, would it be possible for you to merge it?

**Comment by ttillberg** [comment]
@mattgperry are you considering merging / using this fix in framer-motion 3 ? It's still a big problem for applications relying heavily on realtime state updates.

**Comment by rijk** [comment]
I second that. It is occurring on almost every open/close transition I have in my app, making me have to work around it by e.g. delaying the loading of data.

**Comment by Honason** [comment]
This one is important to me too. Without the fix I had to disable framer animations completely.

**Comment by rijk** [comment]
Yes! 🥳🙏

**Pull request closed without merging**
