### PR TITLE
add multidimensional reorder

### PR DESCRIPTION
**Pull request by cjoecker**
As asked in #1400 , here is a PR to allow multidimensional reorder

For now, the user just needs to give the number of items per row. 
In another PR, we can calculate it using the children's refs.

For the docs, do I need to create another PR to adapt it?

### CODE REVIEW

**Comment by mattgperry** [comment]
Hey @cjoecker, thanks for your submission! However I think there's a problem here with the `itemsPerAxis` prop. This doesn't mesh well with dynamic/responsive layouts. Rather than adding a prop the next step for this API would ideally be to remove the `axis` prop. We know the positions of all the children and the order in which they're rendered. So from that we should be able to work out how the list should be sortable.

**Comment by cjoecker** [comment]
Hey @mattgperry , I removed the `axis` and `itemsPerAxis` prop 👏🏻  We should write in the documentation that the multidimensional reordering is only working for items of the same size. 
This can be improved in the future but I keep it simple for now since the logic got pretty complex already. 

Now it is fully responsive. I would just need your help for making it possible to use external refs. I couldn't make it possible to read data from the `reorder` `ref` but also allow an external `ref`.

Can you also tell me how to fix the pipeline? It is asking for a `config` but I couldn't see anything in the documentation about it.

**Comment by cjoecker** [comment]
The PR is ready. I'm just waiting for the maintainers to review it :)

**Comment by TheTimeWalker** [comment]
I'm currently testing this PR out and I have noticed that there seems to be an issue when there's only one item then an uncaught error is being thrown: At least two children components are necessary. This also goes further that when you try to have something like this e.g.

```
        <Reorder.Group
          values={sort}
          onReorder={(newOrder: string[]) => {
            console.log(newOrder);
          }}
        >
          <Reorder.Item key={'value'} value={'value'}>
            <span>test</span>
          </Reorder.Item>
        </Reorder.Group>
```
Then Typescript complains that only a single child has been provided.

**Comment by cjoecker** [comment]
@TheTimeWalker I made that on purpose [here](https://github.com/cjoecker/motion/blob/fdf86df95bb24e4bb035692ae452d0659b423f63/packages/framer-motion/src/components/Reorder/utils/useOrderingParameters.ts#L15-L18).
My idea was to throw an error when `Reorder.Group` has only one child. Like that, the developers will know what is wrong.

**Comment by TheTimeWalker** [comment]
Ah, I see. But wouldn't that break anything when the list only has one item or when <AnimatePresence> is used? This would essentially break examples like this one: https://www.framer.com/docs/reorder/##layout-animations

**Comment by cjoecker** [comment]
@TheTimeWalker good point! Is just fixed it.

**Comment by shandysulen** [comment]
just wanted to a voice a +1, I'm excited for this feature and looking forward to using it for a client project :)

**Comment by mattgperry** [comment]
Hey @cjoecker thanks for your work on this. I'm going to merge it into a branch now and have a play, check tests etc. Hopefully we'll finally have this out soon!

**Comment by joi-lightyears** [comment]
Hi, have you guys merged this?
Because in newer framermotion version I still not use reorder on both axis

**Review by Theghost256 — COMMENTED** [review]
Thank you for your help ☺️🙏

**Review by Theghost256 — COMMENTED** [review]
Thank you for letting me help

**Review by Theghost256 — COMMENTED** [review]
Thank you for letting me help

**Review by Theghost256 — COMMENTED** [review]
Thank you for letting me help 🙂

**Pull request merged**
