### PR TITLE
WIP: Size reduction

### PR DESCRIPTION
**Pull request by InventingWithMonster**
Fixes https://github.com/framer/motion/issues/254

This PR attempts to enable the reduction of the Framer Motion bundle size while not compromising on the simple API.

The outcome will be an unchanged API and bundle size for normal usage, with the option to import a critical-path only version of the `motion` component using something like:

```jsx
import { m as motion } from 'framer-motion'
```

By default, when this component is used, only `initial`, and `style` will be resolved:

```jsx
<motion.div initial={{ opacity: 0 }} style={{ x }} />
```

Supporting this for HTML and SVG will reduce the `m` bundle size down to about 4kb. It might be that we also make SVG support optional and reduce this by another 0.5kb.

From there, a user will be able to add only the features they use via a `MotionConfig` component.

```jsx
import { drag, variants } from 'framer-motion'

// later
export const App = () => {
  return (
    <MotionConfig features={{ drag, variants }}>
      {children}
    </MotionConfig>
  )
}
```

Each added feature will increase the bundle size accordingly.

Depending on a user's needs, some features will be identified as less crucial than others. These can be split out into a separate module and imported dynamically:

```jsx
// features.js
import { drag } from 'framer-motion'
export default { drag }

// index.js
import { useFeatures, variants } from 'framer-motion'

export const App = () => {
  const features = useFeatures(() => import('./features'))
  
  return (
    <MotionConfig features={{ ...features, variants }}>
      {children}
    </MotionConfig>
  )
}
```

This will reduce initial bundle size accordingly.

`MotionConfig` will also allow portions of the tree to be reconfigured with different renderers, for instance a Framer Motion that works with `react-three-fibre`.

### CODE REVIEW

**Comment by otorrillas** [comment]
I have a few of questions about the usage and changes involved:

## Migration strategy

If I understand this correctly:
> The outcome will be an unchanged API and bundle size for normal usage, with the option to import a critical-path only version of the `motion` component using something like:
> 
> ```js-jsx
> import { m as motion } from 'framer-motion'
> ```

For getting the benefits of bundle reduction, we would need to change the default export for a named `m` export. So, from:

```js-jsx
import motion from 'framer-motion'
```
To:
```js-jsx
import { m as motion } from 'framer-motion'
```

Since the change is "straightforward", do you think that providing a [`codemod`](https://github.com/facebook/jscodeshift) could be useful for users with migrating to the new API? I'm more than happy to help with that.

## MotionConfig API

### useFeatures

What's the difference between:

> ```js-jsx
> import { drag, variants } from 'framer-motion'
> 
> // later
> export const App = () => {
>   return (
>     <MotionConfig features={{ drag, variants }}>
>       {children}
>     </MotionConfig>
>   )
> }
> ```

And:

> ```js-jsx
> // features.js
> import { drag } from 'framer-motion'
> export default { drag }
> 
> // index.js
> import { useFeatures, variants } from 'framer-motion'
> 
> export const App = () => {
>   const features = useFeatures(() => import('./features'))
>   
>   return (
>     <MotionConfig features={{ ...features, variants }}>
>       {children}
>     </MotionConfig>
>   )
> }
> ```

Is it that imports in `feature.js` file will be lazy loaded? So they do not influence the initial bundle size? What happens if `motion` library tries to use a feature that is not loaded yet?

### Another approach for lazy loading

Assuming `MotionConfig` is a context provider... what is the expected behavior if we nest `MotionConfig`s? So, we start with "minimal" configuration, but some features are only if their components are loaded? 

Example:
I have an upload section in my app, let's say `UploadPage`, that I lazy load only if the user chooses to upload. 

Something like:
```js-jsx
// app.js
import { variants } from 'framer-motion'

export const App = () => (
  <MotionConfig features={{ variants }}>
        {children}
  </MotionConfig>
)

// upload.js - deeper in the tree
import { drag } from 'framer-motion'

export const Upload = () => (
  <MotionConfig features={{ drag }}>
        {children} // here 
  </MotionConfig>
)
```
Thus, in `Upload` we "extend" the parent `MotionConfig` so we can add more "features" only in trees we need them. But I'm not sure if this over-complicates things.



@InventingWithMonster this is my first time reviewing something in `motion` repository, but I hope you find the feedback useful. Thanks for all the work, `motion` is awesome! 😄

**Comment by InventingWithMonster** [comment]
> Since the change is "straightforward", do you think that providing a [`codemod`](https://github.com/facebook/jscodeshift) could be useful for users with migrating to the new API? I'm more than happy to help with that.

Yeah, I do think it would be that straightforward so a codemod would be helpful here.

> Is it that imports in feature.js file will be lazy loaded? So they do not influence the initial bundle size?

Correct

> What happens if motion library tries to use a feature that is not loaded yet?

Nothing will break. The functionality is already loaded in via renderless components so these will just mount when the functionality loads, and all lifecycle methods will fire as you'd expect (ie mount animations will run). In development, we could generate a one-time warning to remind people to ensure these components are loaded.

> Thus, in Upload we "extend" the parent MotionConfig so we can add more "features" only in trees we need them. But I'm not sure if this over-complicates things.

Yeah I expect `MotionConfig` to be nestable. This will also be how we load in alternative, scoped renderers.

**Comment by ShanonJackson** [comment]
I'd absolutely love to be of help here i'm experienced in making bundles smaller/faster; Iv'e reached out to you on discord Matt for an initial pull request (as you know) however after skimming through why the bundle is so big i think it wouldn't be too much work to slice a large portion of the bundle (however iv'e only skimmed over why the size is what it is).

Some examples of this is in the bundle the entire popmotion library is being included even though you are only using a few exports; This library is required into "motion".

I'd love to help, i can basically rinse/repeat what i'm trying to do in framer-motion in that fork in popmotion and will have same effect, unused exports will be wiped clean.

**Comment by InventingWithMonster** [comment]
With ES6 everything that can be code split already is. Popmotion is
included with everything because it’s used by every animating module
(animation, variants, auto animate and drag). It’ll take this
rearchitecture to allow people to drop the modules they don’t import and in
turn Popmotion will only be included when one of them needs it. Only the
bits and pieces of Popmotion that are used by the respective modules are
imported - it’s full bundle size is 13kb but again that isn’t represented
here.

**Comment by InventingWithMonster** [comment]
Closing this as most of the architectural moves have already been landed in `main`.

**Pull request closed without merging**
